version: '3.4'

services:
  identityDb:
   container_name: identityDb
   environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=admin1234
    - POSTGRES_DB=IdentityDb
   ports:
    - 5432:5432
   volumes:
    - postgres_data:/var/lib/postgresql/data/
   networks:
    - ecoeden_dev_net


  pgadmin:
   image: dpage/pgadmin4
   container_name: pgadmin
   depends_on:
     - identityDb
   environment:
     - PGADMIN_DEFAULT_EMAIL=admin@ecoeden.com
     - PGADMIN_DEFAULT_PASSWORD=admin1234
   ports:
     - "5050:80"
   volumes:
     - pgadmin_data:/root/.pgadmin
   networks:
    - ecoeden_dev_net

  identityserver:
    container_name: Ecoeden.IdentityServer
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - Logging__IncludeScopes=false
      - "Logging__LogOutputTemplate=[{Timestamp:dd-MM-yyyy HH:mm:ss, fff}] {Level} {Properties} [CorrelationId:{CorrelationId}] [Machine: {MachineName}] {CallerType}:{MemberName} {Message}{NewLine}{Exception}{NewLine}"
      - Logging__Console__Enabled=true
      - Logging__Console__LogLevel=Debug
      - Logging__Elastic__Enabled=true
      - Logging__Elastic__LogLevel=Debug
      - AppConfigurations__ApplicationIdentifier=Ecoeden.IdentityService
      - AppConfigurations__ApplicationEnvironment=docker
      - Elasticsearch__Uri=http://elasticsearch:9200
      - ConnectionStrings__DefaultConnection=Server=identityDb;Database=IdentityDb;User Id=admin;Password=admin1234;
    ports:
      - "5000:80"
    depends_on:
      - identityDb
    networks:
      - ecoeden_dev_net
