version: '3.4'

services:
  identityDb:
   image: postgres
  pgadmin:
   image: dpage/pgadmin4

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile

volumes:
  postgres_data:    
  pgadmin_data:
  elasticsearch-data:

